---
apiVersion: v1
kind: Service
metadate:
  name: nginx-svc-external
spec:
  type: ExternalName
  externalName: nginx.qt.com
  selector:
    app: nginx
  ports:
    - name: nginx-pod
      port: 80
      targetPort: 80